import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';
import { Download } from 'lucide-react';

export default function PDFExport({ report, chartRefs }) {
    const generatePDF = async () => {
        // Validate report data
        if (!report || !report.image) {
            alert('No scan data available to export');
            return;
        }

        try {
            const pdf = new jsPDF('p', 'mm', 'a4');
            const pageWidth = pdf.internal.pageSize.getWidth();
            const pageHeight = pdf.internal.pageSize.getHeight();
            let yPos = 20;

            // Cover Page
            pdf.setFillColor(139, 92, 246);
            pdf.rect(0, 0, pageWidth, pageHeight / 3, 'F');

            pdf.setFillColor(236, 72, 153);
            pdf.rect(0, pageHeight / 3, pageWidth, pageHeight / 3, 'F');

            pdf.setFont('helvetica', 'bold');
            pdf.setFontSize(32);
            pdf.setTextColor(255, 255, 255);
            pdf.text('Docker Security', pageWidth / 2, 60, { align: 'center' });
            pdf.text('Analysis Report', pageWidth / 2, 75, { align: 'center' });

            pdf.setFontSize(18);
            pdf.text(report.image || 'Unknown Image', pageWidth / 2, 95, { align: 'center' });

            const verdictColors = {
                SAFE: [16, 185, 129],
                SUSPICIOUS: [245, 158, 11],
                RISKY: [239, 68, 68],
            };
            const color = verdictColors[report.verdict] || [100, 116, 139];

            pdf.setFillColor(...color);
            pdf.roundedRect(pageWidth / 2 - 30, 110, 60, 20, 5, 5, 'F');
            pdf.setFontSize(16);
            pdf.setFont('helvetica', 'bold');
            pdf.text(report.verdict || 'UNKNOWN', pageWidth / 2, 123, { align: 'center' });

            pdf.setFont('helvetica', 'normal');
            pdf.setFontSize(10);
            pdf.setTextColor(220, 220, 220);
            pdf.text(`Scan ID: ${report.scan_id || 'N/A'}`, pageWidth / 2, 145, { align: 'center' });
            pdf.text(`Date: ${new Date(report.timestamp || Date.now()).toLocaleString()}`, pageWidth / 2, 152, { align: 'center' });

            pdf.text('Generated by eDockScan v1.0', pageWidth / 2, pageHeight - 10, { align: 'center' });

            // Page 2: Executive Summary
            pdf.addPage();
            yPos = 20;

            pdf.setTextColor(0, 0, 0);
            pdf.setFont('helvetica', 'bold');
            pdf.setFontSize(18);
            pdf.text('Executive Summary', 20, yPos);
            yPos += 15;

            pdf.setFont('helvetica', 'normal');
            pdf.setFontSize(10);

            const metrics = [
                { label: 'Risk Score', value: `${Math.round((report.risk_score || 0) * 100)}%`, color },
                { label: 'Confidence', value: report.confidence || 'N/A', color: [100, 116, 139] },
                { label: 'Severity', value: report.severity || 'N/A', color: [100, 116, 139] },
                { label: 'Known CVEs', value: String(report.all_features?.known_cves || 0), color: [239, 68, 68] },
            ];

            metrics.forEach((metric, index) => {
                const xPos = 20 + (index % 2) * 90;
                const yOffset = Math.floor(index / 2) * 30;

                pdf.setFillColor(248, 250, 252);
                pdf.roundedRect(xPos, yPos + yOffset, 80, 25, 3, 3, 'F');

                pdf.setDrawColor(226, 232, 240);
                pdf.roundedRect(xPos, yPos + yOffset, 80, 25, 3, 3, 'S');

                pdf.setTextColor(100, 116, 139);
                pdf.setFontSize(9);
                pdf.text(metric.label, xPos + 5, yPos + yOffset + 8);

                pdf.setFontSize(16);
                pdf.setFont('helvetica', 'bold');
                pdf.setTextColor(...metric.color);
                pdf.text(metric.value, xPos + 5, yPos + yOffset + 20);
                pdf.setFont('helvetica', 'normal');
            });

            yPos += 70;

            // Page 3: Detailed Findings
            pdf.addPage();
            yPos = 20;

            pdf.setFont('helvetica', 'bold');
            pdf.setFontSize(18);
            pdf.setTextColor(0, 0, 0);
            pdf.text('Detailed Findings', 20, yPos);
            yPos += 10;

            pdf.setFontSize(14);
            pdf.text('Top Risk Factors', 20, yPos);
            yPos += 8;

            pdf.setFont('helvetica', 'normal');
            pdf.setFontSize(10);

            // FIX: top_risk_factors is an array of objects, not strings
            const topFactors = report.top_risk_factors || [];
            topFactors.slice(0, 10).forEach((factor, index) => {
                if (yPos > pageHeight - 20) {
                    pdf.addPage();
                    yPos = 20;
                }
                const factorText = `${index + 1}. ${factor.feature?.replace(/_/g, ' ') || 'Unknown'}: ${factor.value || 0} (${Math.round((factor.importance || 0) * 100)}%)`;
                pdf.text(factorText, 25, yPos);
                yPos += 6;
            });

            yPos += 5;

            if (yPos > pageHeight - 60) {
                pdf.addPage();
                yPos = 20;
            }

            // Layer Analysis
            if (report.layer_analyses && report.layer_analyses.length > 0) {
                pdf.setFont('helvetica', 'bold');
                pdf.setFontSize(14);
                pdf.text('Layer Analysis', 20, yPos);
                yPos += 8;

                autoTable(pdf, {
                    startY: yPos,
                    head: [['Layer', 'Command', 'Risk Score']],
                    body: report.layer_analyses.slice(0, 15).map((layer, idx) => [
                        String(idx + 1),
                        (layer.command || 'Unknown').substring(0, 50) + ((layer.command || '').length > 50 ? '...' : ''),
                        `${Math.round((layer.risk_score || 0) * 100)}%`,
                    ]),
                    styles: { fontSize: 9, cellPadding: 2 },
                    headStyles: { fillColor: [139, 92, 246], textColor: 255 },
                    alternateRowStyles: { fillColor: [248, 250, 252] },
                });

                yPos = pdf.lastAutoTable.finalY + 10;
            }

            // Page 4: Remediations
            if (report.remediations && report.remediations.length > 0) {
                if (yPos > pageHeight - 60) {
                    pdf.addPage();
                    yPos = 20;
                }

                pdf.setFont('helvetica', 'bold');
                pdf.setFontSize(18);
                pdf.text('Remediation Recommendations', 20, yPos);
                yPos += 10;

                autoTable(pdf, {
                    startY: yPos,
                    head: [['Severity', 'Issue', 'Recommendation']],
                    body: report.remediations.slice(0, 15).map(rem => [
                        rem.severity || 'UNKNOWN',
                        (rem.issue || 'No description').substring(0, 50) + ((rem.issue || '').length > 50 ? '...' : ''),
                        (rem.remediation || 'No recommendation').substring(0, 60) + ((rem.remediation || '').length > 60 ? '...' : ''),
                    ]),
                    styles: { fontSize: 9, cellPadding: 3 },
                    headStyles: { fillColor: [139, 92, 246], textColor: 255 },
                    columnStyles: {
                        0: { cellWidth: 25 },
                        1: { cellWidth: 70 },
                        2: { cellWidth: 85 },
                    },
                });
            }

            // Add footer
            const totalPages = pdf.getNumberOfPages();
            for (let i = 1; i <= totalPages; i++) {
                pdf.setPage(i);
                pdf.setFontSize(8);
                pdf.setTextColor(150, 150, 150);
                pdf.text(`Page ${i} of ${totalPages}`, pageWidth - 20, pageHeight - 10, { align: 'right' });
            }

            pdf.save(`eDockScan_${report.image.replace(/[/:]/g, '_')}_${Date.now()}.pdf`);
        } catch (error) {
            console.error('PDF generation failed:', error);
            alert(`Failed to generate PDF: ${error.message}`);
        }
    };

    return (
        <button
            onClick={generatePDF}
            className="flex items-center space-x-2 bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 px-4 py-2 rounded-lg text-white font-semibold transition-all"
        >
            <Download className="w-4 h-4" />
            <span>Export PDF Report</span>
        </button>
    );
}